id=com.easyshow.tv
name=EasyShow_PPT
mainURL=https://easyshow.beundredig.eu.org/remote.html?room=admin&mode=tv
forceLandscapeMode=true
JSEnabled=true
DomStorageEnabled=true
FullscreenVideoEnabled=true
KeepScreenOn=true
