id=com.easyshow.tv
name=EasyShow
mainURL=https://easyshow.beundredig.eu.org/remote.html?room=admin&mode=tv
forceLandscapeMode=true
MediaPlaybackRequiresUserGesture=false
allowMixedContent=true
DomStorageEnabled=true
cacheMode=no_cache
scripts=scripts/*.js
cameraEnabled=true
microphoneEnabled=true
geolocationEnabled=true
trustUserCA=true
JSEnabled=true
AllowFileAccess=true
AllowFileAccessFromFileURLs=true
SavePassword=true
confirmOpenInBrowser=false
confirmOpenExternalApp=false
showDetailsOnErrorScreen=true
